### ISSUE TITLE
TAG_MAPPING_FILE for human disease ontology genesets

### ISSUE THREAD

**Issue by dongbohu** [greenelab/disease_ontology_geneset#2]
When generating human disease ontology genesets, [greenelab/annotation-refinery](https://github.com/greenelab/annotation-refinery) also reads in `TAG_MAPPING_FILE`, which is defined here:
https://github.com/greenelab/annotation-refinery/blob/0cee50b6ae101c6df42719ab55db0ffeea1221b6/species_files/human.ini#L52
```
TAG_MAPPING_FILE: tag_mapping_files/tissue-disease_curated-associations.txt
```
This file hasn't been updated for 5 years:
https://github.com/greenelab/annotation-refinery/blob/master/tag_mapping_files/tissue-disease_curated-associations.txt
I am not sure whether we still want to load its content. @cgreene?

**Comment by cgreene** [comment]
Agree we can drop it. Not sure where that was derived from.

**Comment by dongbohu** [comment]
Dropped in this commit: https://github.com/greenelab/disease_ontology_geneset/commit/5d8822b02bffe7bccbe4f3faa45883d84101ab95
